//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClothing
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public decimal Price { get; set; }
        public int ColorID { get; set; }
    
        public virtual TblColor TblColor { get; set; }
        public virtual TblItem TblItem { get; set; }
    }
}
